import Link from "next/link";
import { ArrowRight, CircleDollarSign, Clock3, Factory, PackageCheck, ShoppingCart, Truck } from "lucide-react";
import OrdersTable from "@/components/admin/OrdersTable";
import { formatAdminPrice, orders } from "@/lib/admin/orders-data";

export default function AdminDashboardPage() {
  const monthRevenue = orders.filter((order) => order.paymentStatus === "paid").reduce((sum, order) => sum + order.totalHt, 0);
  const inProduction = orders.filter((order) => ["engineering", "production", "quality-control"].includes(order.status)).length;
  const toShip = orders.filter((order) => order.status === "ready-to-ship").length;
  return <main className="mx-auto w-full max-w-[1600px] p-4 md:p-7 xl:p-9">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.22em] text-orange-600">Vendredi 17 juillet 2026</p><h1 className="mt-2 text-3xl font-black tracking-tight text-slate-950 md:text-4xl">Pilotage OYSTE</h1><p className="mt-2 text-sm text-slate-500">Commandes, production et expéditions réunies dans un seul espace.</p></div><Link href="/admin/commandes" className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-xs font-black uppercase tracking-wide text-white transition hover:bg-[#006d79]">Voir les commandes <ArrowRight size={16} /></Link></div>
    <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[
      { label: "Nouvelles commandes", value: "6", hint: "2 depuis ce matin", icon: ShoppingCart, tone: "text-orange-600 bg-orange-50" },
      { label: "À encaisser", value: "2", hint: "8 460 € TTC", icon: Clock3, tone: "text-amber-700 bg-amber-50" },
      { label: "En production", value: String(inProduction), hint: "Étude + atelier", icon: Factory, tone: "text-violet-700 bg-violet-50" },
      { label: "À expédier", value: String(toShip), hint: "Aujourd’hui", icon: Truck, tone: "text-sky-700 bg-sky-50" },
      { label: "CA du mois", value: formatAdminPrice(monthRevenue), hint: "+14,2 % vs juin", icon: CircleDollarSign, tone: "text-emerald-700 bg-emerald-50" },
    ].map((card) => { const Icon = card.icon; return <article key={card.label} className="rounded-[1.4rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-[9px] font-black uppercase tracking-[0.15em] text-slate-400">{card.label}</p><p className="mt-3 text-2xl font-black tracking-tight text-slate-950">{card.value}</p></div><div className={`flex h-10 w-10 items-center justify-center rounded-2xl ${card.tone}`}><Icon size={19} /></div></div><p className="mt-4 text-xs font-bold text-slate-500">{card.hint}</p></article>; })}</section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_360px]"><div><div className="mb-3 flex items-center justify-between"><div><h2 className="text-lg font-black">Dernières commandes</h2><p className="mt-1 text-xs text-slate-500">Les dossiers les plus récents à suivre.</p></div><Link href="/admin/commandes" className="text-xs font-black text-[#006d79]">Tout afficher</Link></div><OrdersTable records={orders.slice(0, 5)} compact /></div><div className="space-y-6"><article className="rounded-[1.4rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-700"><PackageCheck size={20} /></div><div><h2 className="text-lg font-black">Flux opérationnel</h2><p className="text-xs text-slate-500">État des commandes actives</p></div></div><div className="mt-6 space-y-4">{[{ label: "Étude", value: 1, width: "24%" }, { label: "Fabrication", value: 1, width: "48%" }, { label: "Contrôle qualité", value: 1, width: "70%" }, { label: "Prêtes à expédier", value: 1, width: "94%" }].map((item) => <div key={item.label}><div className="mb-2 flex justify-between text-xs"><span className="font-black text-slate-700">{item.label}</span><span className="font-black">{item.value}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#007f8f]" style={{ width: item.width }} /></div></div>)}</div></article><article className="rounded-[1.4rem] bg-[#07131f] p-5 text-white shadow-xl"><p className="text-[9px] font-black uppercase tracking-[0.22em] text-cyan-300">Point d’attention</p><h2 className="mt-2 text-xl font-black">1 expédition aujourd’hui</h2><p className="mt-2 text-xs leading-5 text-white/55">La commande CMD-2026-0713 est emballée et attend le transporteur à 14 h.</p><Link href="/admin/expeditions" className="mt-5 inline-flex items-center gap-2 text-xs font-black text-orange-400">Ouvrir la logistique <ArrowRight size={14} /></Link></article></div></section>
  </main>;
}
