"use client";
import { ArrowRight } from "lucide-react";
export type CapacityRecommendation = { id: string; name: string; href: string; imageUrl: string; type: string; priceLabel: string; capacitiesKg: number[] };
export default function CapacityRecommendations({ items, selectedCapacityKg }: { items: CapacityRecommendation[]; selectedCapacityKg: number | null }) {
  if (!selectedCapacityKg) return null;
  const recommendations = items.filter((item) => item.capacitiesKg.some((capacity) => capacity >= selectedCapacityKg)).sort((a, b) => Math.min(...a.capacitiesKg.filter((value) => value >= selectedCapacityKg)) - Math.min(...b.capacitiesKg.filter((value) => value >= selectedCapacityKg))).slice(0, 4);
  if (!recommendations.length) return null;
  return <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><p className="text-xs font-black uppercase tracking-[0.18em] text-orange-600">Présélection selon la CMU</p><h2 className="mt-1 text-2xl font-black text-slate-950">Complétez votre installation</h2><p className="mt-1 text-xs font-semibold text-slate-500">Solutions dont la capacité renseignée est au moins égale à {selectedCapacityKg >= 1000 ? `${selectedCapacityKg / 1000} t` : `${selectedCapacityKg} kg`}. Les autres paramètres d’installation restent à vérifier.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{recommendations.map((item) => { const capacity = Math.min(...item.capacitiesKg.filter((value) => value >= selectedCapacityKg)); return <a key={item.id} href={item.href} className="group grid grid-cols-[76px_1fr] gap-3 rounded-xl border border-slate-200 p-3 transition hover:border-orange-400 hover:shadow-md"><div className="flex h-[72px] items-center justify-center overflow-hidden rounded-lg bg-slate-50"><img src={item.imageUrl} alt="" className="h-full w-full object-contain p-2" /></div><div className="min-w-0"><p className="truncate text-[10px] font-black uppercase tracking-[0.12em] text-orange-600">{item.type}</p><h3 className="mt-1 line-clamp-2 text-sm font-black leading-5 text-slate-950">{item.name}</h3><p className="mt-1 text-[11px] font-bold text-slate-500">CMU {capacity >= 1000 ? `${capacity / 1000} t` : `${capacity} kg`}</p><p className="mt-1 flex items-center gap-1 text-xs font-black text-[#007f8f]">{item.priceLabel} <ArrowRight size={12} /></p></div></a>; })}</div></section>;
}
