import {test,beforeEach} from 'node:test';import assert from 'node:assert/strict';import Module from 'node:module';
let admin:any;
function replace(path:string,exports:any){const filename=require.resolve(path),m=new Module(filename);m.filename=filename;m.loaded=true;m.exports=exports;require.cache[filename]=m;}
replace('../../auth/admin-session',{getCurrentAdmin:async()=>admin});replace('@vercel/blob/client',{handleUpload:async({body,onBeforeGenerateToken}:any)=>({constraints:await onBeforeGenerateToken(body.pathname,body.clientPayload)})});
const api=require('../../../app/api/admin/assets/upload/route') as typeof import('../../../app/api/admin/assets/upload/route');
const request=(scope:string,pathname=`site-assets/${scope}/file.png`)=>new Request('https://oyste.test/api',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pathname,clientPayload:JSON.stringify({scope})})});
beforeEach(()=>{admin={id:'admin',role:'SUPER_ADMIN'};});
test('assets : anonymes et rôle lecture seule refusés sans token',async()=>{admin=null;assert.equal((await api.POST(request('cms'))).status,401);admin={id:'a',role:'ORDER_MANAGER'};assert.equal((await api.POST(request('cms'))).status,403);});
test('assets : séparation des permissions éditoriales et catalogue',async()=>{admin.role='CONTENT_EDITOR';assert.equal((await api.POST(request('cms'))).status,200);assert.equal((await api.POST(request('suppliers'))).status,403);admin.role='CATALOG_MANAGER';assert.equal((await api.POST(request('documents'))).status,200);assert.equal((await api.POST(request('cms'))).status,403);});
test('assets : documents PDF limités et images sans fichiers exécutables',async()=>{const pdf=await(await api.POST(request('documents'))).json();assert.deepEqual(pdf.constraints.allowedContentTypes,['application/pdf']);assert.equal(pdf.constraints.maximumSizeInBytes,25*1024*1024);const image=await(await api.POST(request('catalogue'))).json();assert.ok(image.constraints.allowedContentTypes.includes('image/jpeg'));assert.ok(!image.constraints.allowedContentTypes.includes('text/html'));assert.equal(image.constraints.maximumSizeInBytes,10*1024*1024);});
test('assets : chemin hors destination et traversée refusés',async()=>{assert.equal((await api.POST(request('cms','products/OTHER/x.png'))).status,400);assert.equal((await api.POST(request('cms','site-assets/cms/../suppliers/x.png'))).status,400);assert.equal((await api.POST(request('inconnue'))).status,400);});
