import { test } from 'node:test';
import assert from 'node:assert/strict';
import { applyProductPresentation, applyVariantPresentation, productPresentationSchema } from '../../catalogue/product-presentation';
import { getProductMarketingBadges,getProductFaq,getProductCardImages,getProductAvailableDocumentCount,type CatalogueProduct } from '../../catalogue/repository';
import { legacyCategories,legacySuppliers } from '../../catalogue/presentation-defaults';
import { editorialDefaults,editorialDescriptors } from '../../editorial-defaults';
import { validateEditorial,mergeEditorial,safeEditorialLink,type EditorialPageId } from '../../editorial-validation';
import { variantInputSchema,isAdminVariant } from '../variant-validation';
const source:CatalogueProduct={id:'p1',code:'SRC',supplierCode:'SRC',parentCode:'',slug:'source',name:'Source',shortName:'Source',manufacturer:'STOCKMAN',categorySlug:'levage',categoryPath:'Levage',categories:['Levage'],description:'Description fournisseur',detailedDescription:'Texte fournisseur',priceHT:123,stock:4,delay:'10 jours',imageRef:'SRC',features:[{label:'Source',value:'Oui'}],href:'/catalogue/levage/source',media:[{url:'https://supplier.test/source.jpg'}],documents:[{name:'Source',url:'https://supplier.test/source.pdf',type:'OTHER',isPublic:true}],variants:[{id:'v1',code:'S1',supplierCode:'S1',name:'Variante',label:'Source',priceHT:456,delay:'10 jours',stock:3,imageRef:'S1',features:[],options:{}}]};
test('override commercial : le front reçoit les textes, badges, FAQ, vidéos, références et caractéristiques',()=>{const output=applyProductPresentation(source,{name:'Nom BO',featured:true,sortOrder:2,marketingBadges:['Nouveau'],faq:[{question:'Question ?',answer:'Réponse'}],videoUrls:['https://example.test/video.mp4'],relatedProductCodes:['R1'],accessoryProductCodes:['A1'],features:[{label:'BO',value:'Valeur'}]});assert.equal(output.name,'Nom BO');assert.equal(output.featured,true);assert.equal(output.sortOrder,2);assert.deepEqual(getProductMarketingBadges(output),['Nouveau']);assert.deepEqual(getProductFaq(output),[{question:'Question ?',answer:'Réponse'}]);assert.deepEqual(output.features,[{label:'BO',value:'Valeur'}]);assert.equal(output.videoUrls?.length,1);assert.deepEqual(output.relatedProductCodes,['R1']);assert.deepEqual(output.accessoryProductCodes,['A1']);assert.equal(output.priceHT,123);assert.equal(output.supplierCode,'SRC');assert.equal(source.name,'Source');});
test('synchronisation source : override conservé, valeurs techniques actualisées, suppression override rétablit la dernière source',()=>{const synchronized={...source,name:'Source mise à jour',priceHT:999,stock:22,description:'Dernière description'};const override={name:'Choix BO'};assert.equal(applyProductPresentation(synchronized,override).name,'Choix BO');assert.equal(applyProductPresentation(synchronized,override).priceHT,999);assert.equal(applyProductPresentation(synchronized,{}).name,'Source mise à jour');assert.equal(applyProductPresentation(synchronized,{}).description,'Dernière description');});
test('collections vides explicites : aucun retour des images, badges, FAQ ou documents importés',()=>{const output=applyProductPresentation(source,{media:[],marketingBadges:[],faq:[],documents:[],features:[]});assert.deepEqual(getProductCardImages(output),[]);assert.deepEqual(getProductMarketingBadges(output),[]);assert.deepEqual(getProductFaq(output),[]);assert.equal(getProductAvailableDocumentCount(output),0);assert.deepEqual(output.features,[]);});
test('médias : visibilité, ordre et image principale sont utilisés par les cartes et la fiche',()=>{const output=applyProductPresentation(source,{media:[{url:'/images/a.png',sortOrder:0,isPrimary:false,enabled:true,altText:''},{url:'/images/main.png',sortOrder:9,isPrimary:true,enabled:true,altText:''},{url:'/images/hidden.png',sortOrder:0,isPrimary:false,enabled:false,altText:''}]});assert.deepEqual(getProductCardImages(output),['/images/main.png','/images/a.png']);});
test('médias : plusieurs images principales sont refusées',()=>{assert.equal(productPresentationSchema.safeParse({media:[{url:'/a.png',sortOrder:0,isPrimary:true},{url:'/b.png',sortOrder:1,isPrimary:true}]}).success,false);});
test('variantes : libellé, ordre, visibilité ; source conservée et prix non modifié',()=>{const first=source.variants![0],second={...first,id:'v2',code:'S2'};const output=applyVariantPresentation([first,second],[{id:'v1',label:'Masquée',enabled:false,sortOrder:0},{id:'v2',label:'Choix BO',enabled:true,sortOrder:1}]);assert.equal(output.length,1);assert.equal(output[0].label,'Choix BO');assert.equal(output[0].priceHT,456);assert.equal(first.label,'Source');assert.deepEqual(applyVariantPresentation([first],[{id:'v1',label:'',enabled:false,sortOrder:0}]),[]);});
for(const key of ['priceHt','stock','supplierId','sourceData'])test(`override : champ technique ${key} rejeté`,()=>assert.equal(productPresentationSchema.safeParse({[key]:1}).success,false));
for(const url of ['javascript:alert(1)','//evil.test','data:text/html,test','/\\evil.test'])test(`override : URL dangereuse ${url} rejetée`,()=>assert.equal(productPresentationSchema.safeParse({videoUrls:[url]}).success,false));
test('défauts home : cinq univers et huit fournisseurs avec images et ordres historiques',()=>{const categories=legacyCategories(),roots=categories.filter(item=>!item.homeParentId);assert.equal(roots.length,5);assert.deepEqual(roots.map(item=>item.homeLabel),['Levage','Manutention','Motorisation SEW','Stockage','Accès hauteur']);assert.ok(roots.every(item=>item.homeImageUrl&&item.homeVisible));assert.deepEqual(legacySuppliers.map(item=>item.name),['ADEI','KITO','STOCKMAN','SEW USOCOME','CROMOX','HYDROBULL','COMEPAL','GOLIATH']);assert.ok(legacySuppliers.every((item,i)=>item.homeOrder===i&&item.logoUrl&&item.homeVisible));const palan=categories.find(item=>item.publicFamilySlug==='palan');assert.ok(palan?.imageUrl);assert.equal(palan?.homeImageUrl,palan?.imageUrl);});
for(const id of Object.keys(editorialDefaults) as EditorialPageId[])test(`page ${id} : défauts valides, contenus non vides et absence de perte au premier enregistrement`,()=>{assert.ok(validateEditorial(id,editorialDefaults[id]));assert.deepEqual(mergeEditorial(id,null),editorialDefaults[id]);assert.ok(Object.keys(editorialDefaults[id].fields).length);assert.ok(editorialDescriptors[id].title);});
test('CMS page : liste supprimée reste vide et édition texte réellement fusionnée',()=>{const output=mergeEditorial('about',{fields:{content001:'Nouveau titre'},collections:{commitments:[]}});assert.equal(output.fields.content001,'Nouveau titre');assert.deepEqual(output.collections.commitments,[]);assert.ok(output.fields.content002);});
test('CMS page : lien dangereux, champ inconnu et bloc mal formé refusés',()=>{const link=editorialDescriptors.about.fields.find(field=>field.kind==='link')!;assert.equal(validateEditorial('about',{fields:{[link.key]:'javascript:alert(1)'},collections:{}}),null);assert.equal(validateEditorial('about',{fields:{technical:'oops'},collections:{}}),null);assert.equal(validateEditorial('about',{fields:{},collections:{commitments:[{title:'Vide'}]}}),null);assert.equal(safeEditorialLink('/\\evil.test'),false);assert.equal(safeEditorialLink('mailto:contact@oyste.fr'),true);assert.equal(safeEditorialLink('#contact-form'),true);});
test('variante BO : validation des montants et protection de la provenance',()=>{const data={code:'BO-1',name:'Variante',label:'BO',priceHt:12,stock:0,weightKg:null,packageLengthCm:null,packageWidthCm:null,packageHeightCm:null,leadTime:'',imageReference:'',shippingMode:null,options:[]};assert.ok(variantInputSchema.safeParse(data).success);assert.equal(variantInputSchema.safeParse({...data,priceHt:-1}).success,false);assert.equal(variantInputSchema.safeParse({...data,sourceData:{adminCreated:true}}).success,false);assert.equal(isAdminVariant({adminCreated:true}),true);assert.equal(isAdminVariant({supplier:true}),false);});

test('sections éditoriales : visibilité et ordre conservés sans vider les valeurs historiques',()=>{const sections=editorialDefaults.about.collections.pageSections.map((item,index)=>({...item,enabled:index!==0,order:10-index}));const output=mergeEditorial('about',{fields:{},collections:{pageSections:sections}});const visible=output.collections.pageSections.filter(item=>item.enabled).sort((a,b)=>a.order-b.order);assert.equal(visible.length,sections.length-1);assert.equal(visible[0].id,sections.at(-1)?.id);assert.equal(output.fields.content001,editorialDefaults.about.fields.content001);});
test('sections éditoriales : identifiant inventé ou doublon rejeté',()=>{const sections=editorialDefaults.about.collections.pageSections;assert.equal(validateEditorial('about',{fields:{},collections:{pageSections:sections.map((item,i)=>({...item,id:i===0?'inconnue':item.id}))}}),null);});

test('parcours public : standard/configurateur et CTA modifiables indépendamment de la source',()=>{const {getProductExperienceType,getProductConfiguratorHref}=require('../../catalogue/repository');const output=applyProductPresentation(source,{experienceType:'CONFIGURABLE',configuratorHref:'/configurateur?famille=PFI'});assert.equal(getProductExperienceType(output),'CONFIGURABLE');assert.equal(getProductConfiguratorHref(output),'/configurateur?famille=PFI');assert.equal(source.experienceType,undefined);});

test('ajout de variante BO sur un import plat : les variantes fournisseur restent proposées',()=>{const {resolvePresentedVariants}=require('../../catalogue/product-presentation');const first=source.variants![0],second={...first,id:'v2',code:'S2'},manual={...first,id:'admin',code:'BO'};const output=resolvePresentedVariants({...source,variants:[manual],baseVariants:[manual],includeSupplierFamilyVariants:true},[first,second]);assert.deepEqual(output.map((item:any)=>item.code),['S1','S2','BO']);});

test('nom court BO : titre des cartes modifié, titre de fiche complet conservé',()=>{const {getProductCardTitle}=require('../../catalogue/repository');assert.equal(getProductCardTitle(source),'Source');const output=applyProductPresentation(source,{shortName:'Titre de carte BO'});assert.equal(getProductCardTitle(output),'Titre de carte BO');assert.equal(output.name,'Source');});
