import { test,beforeEach } from 'node:test';import assert from 'node:assert/strict';import Module from 'node:module';
let admin:any;let calls=0;const categories=new Map<string,any>(),suppliers=new Map<string,any>(),products=new Map<string,any>(),overrides=new Map<string,any>(),settings=new Map<string,any>(),variants=new Map<string,any>();let sequence=0;let audit:any[]=[];
function matches(item:any,where:any):boolean {return Object.entries(where||{}).every(([key,value]:any)=>{if(key==='OR')return value.some((condition:any)=>matches(item,condition));if(value&&typeof value==='object'){if('in'in value)return value.in.includes(item[key]);if('not'in value)return item[key]!==value.not;if('equals'in value)return String(item[key]).toLowerCase()===String(value.equals).toLowerCase();return true;}return item[key]===value;});}
function model(store:Map<string,any>,key='id'){return {findUnique:async({where}:any)=>[...store.values()].find(item=>matches(item,where))||null,findFirst:async({where}:any)=>[...store.values()].find(item=>matches(item,where))||null,findMany:async({where}:any={})=>[...store.values()].filter(item=>matches(item,where)),create:async({data}:any)=>{calls++;const item={id:`item-${++sequence}`,variants:[],media:[],documents:[],features:[],_count:{orderItems:0},...data};store.set(item[key],item);return item;},update:async({where,data}:any)=>{calls++;const old=[...store.values()].find(item=>matches(item,where));const item={...old,...data};store.set(item[key],item);return item;},upsert:async({where,update,create}:any)=>{calls++;const old=[...store.values()].find(item=>matches(item,where));const item=old?{...old,...update}:{id:`item-${++sequence}`,...create};store.set(item[key],item);return item;},delete:async({where}:any)=>{calls++;const old=[...store.values()].find(item=>matches(item,where));store.delete(old[key]);return old;}};}
const db:any={category:model(categories),supplier:model(suppliers),product:model(products),productPresentationOverride:model(overrides,'productId'),siteSetting:model(settings,'key'),productVariant:model(variants),auditLog:{create:async(data:any)=>{audit.push(data);return data;}},$executeRaw:async()=>{},$transaction:async(callback:any)=>Array.isArray(callback)?Promise.all(callback):callback(db)};
function replace(path:string,exports:any){const filename=require.resolve(path),m=new Module(filename);m.filename=filename;m.loaded=true;m.exports=exports;require.cache[filename]=m;}
replace('../../db/prisma',{prisma:db});replace('../../auth/admin-session',{getCurrentAdmin:async()=>admin});replace('../../catalogue/database-repository',{getDatabaseProductsByCategory:async()=>[],getDatabaseStockmanFamilyVariants:async()=>({variants:[],optionSchema:[]})});
const presentation=require('../../../app/api/admin/catalogue/[id]/presentation/route') as typeof import('../../../app/api/admin/catalogue/[id]/presentation/route');const editorial=require('../../../app/api/admin/editorial/[page]/route') as typeof import('../../../app/api/admin/editorial/[page]/route');const references=require('../reference-api') as typeof import('../reference-api');const publicPresentation=require('../../catalogue/public-presentation') as typeof import('../../catalogue/public-presentation');const initializer=require('../initialize-presentation') as typeof import('../initialize-presentation');const variantApi=require('../../../app/api/admin/catalogue/[id]/variants/route') as typeof import('../../../app/api/admin/catalogue/[id]/variants/route');
const request=(body:any,method='PUT')=>new Request('https://oyste.test/api',{method,headers:{'content-type':'application/json'},body:JSON.stringify(body)}),context={params:Promise.resolve({id:'p1'})};
beforeEach(()=>{[categories,suppliers,products,overrides,settings,variants].forEach(store=>store.clear());calls=0;audit=[];admin={id:'admin',role:'SUPER_ADMIN'};products.set('p1',{id:'p1',code:'SRC',name:'Source',variants:[],media:[],documents:[],features:[],presentation:null});});
test('API présentation : écriture séparée, relecture BO et aucune mutation des données source',async()=>{assert.equal((await presentation.PUT(request({name:'Nom BO',featured:true,faq:[]}),context)).status,200);assert.equal(products.get('p1').name,'Source');assert.deepEqual(overrides.get('p1').value,{name:'Nom BO',featured:true,faq:[]});products.get('p1').presentation=overrides.get('p1');const result=await(await presentation.GET(request({}),context)).json();assert.equal(result.overrides.name,'Nom BO');assert.equal(audit.length,1);});
test('API présentation : références associées inexistantes et variantes étrangères refusées',async()=>{assert.equal((await presentation.PUT(request({relatedProductCodes:['MISSING']}),context)).status,400);assert.equal((await presentation.PUT(request({variantPresentation:[{id:'other',label:'',sortOrder:0,enabled:false}]}),context)).status,400);assert.equal(overrides.size,0);});
test('API présentation : anonymes et rôle contenu ne peuvent écrire',async()=>{admin=null;assert.equal((await presentation.PUT(request({name:'Interdit'}),context)).status,401);admin={id:'a',role:'CONTENT_EDITOR'};assert.equal((await presentation.PUT(request({name:'Interdit'}),context)).status,403);assert.equal(calls,0);});
test('API éditorial : persistance SiteSetting puis relecture publique du même texte',async()=>{admin.role='CONTENT_EDITOR';const context={params:Promise.resolve({page:'about'})};assert.equal((await editorial.PUT(request({fields:{content001:'Titre commercial BO'},collections:{commitments:[]}}),context)).status,200);const {getEditorialPage}=require('../../editorial');const page=await getEditorialPage('about');assert.equal(page.fields.content001,'Titre commercial BO');assert.deepEqual(page.collections.commitments,[]);assert.equal((await editorial.GET(request({}),context)).status,200);});
test('API éditorial : rôle catalogue et URL dangereuse refusés',async()=>{const context={params:Promise.resolve({page:'about'})};admin.role='CATALOG_MANAGER';assert.equal((await editorial.PUT(request({fields:{},collections:{}}),context)).status,403);admin.role='CONTENT_EDITOR';const {editorialDescriptors}=require('../../editorial-defaults');const link=editorialDescriptors.about.fields.find((item:any)=>item.kind==='link');assert.equal((await editorial.PUT(request({fields:{[link.key]:'javascript:alert(1)'},collections:{}}),context)).status,400);assert.equal(settings.size,0);});
test('home avant initialisation : rendu historique non vide',async()=>{const result=await publicPresentation.getPublicPresentation();assert.equal(result.ready,false);assert.equal(result.categories.filter(item=>!item.homeParentId).length,5);assert.equal(result.suppliers.length,8);});
test('initialisation idempotente : parents réels, images conservées, fournisseurs d’intégration non renommés',async()=>{suppliers.set('existing',{id:'existing',name:'Stockman',slug:'stockman',supplierCode:'STOCKMAN',isActive:true,presentationConfigured:false});const result=await initializer.initializePresentation(db);assert.equal(result.alreadyInitialized,false);assert.equal(settings.get('cms.catalogue.ready').value,true);const root=[...categories.values()].find(item=>item.slug==='levage'),palan=[...categories.values()].find(item=>item.publicFamilySlug==='palan');assert.equal(palan.homeParentId,root.id);assert.ok(palan.homeImageUrl);assert.equal(suppliers.get('existing').name,'Stockman');assert.equal(suppliers.get('existing').supplierCode,'STOCKMAN');assert.ok(products.has('virtual-potence-sur-fut'));const count=calls;assert.equal((await initializer.initializePresentation(db)).alreadyInitialized,true);assert.equal(calls,count);});
test('BO catégorie vers home : visibilité, ordre, image et libellé réellement utilisés',async()=>{settings.set('cms.catalogue.ready',{key:'cms.catalogue.ready',value:true});categories.set('c',{id:'c',name:'Catégorie',slug:'cat',parentId:null,homeParentId:null,imageUrl:'/old.png',isActive:true,sortOrder:0,publicTags:[],presentationConfigured:true,representativeProduct:null,products:[]});const input={name:'Catégorie',slug:'cat',parentId:null,description:null,seoTitle:null,seoDescription:null,imageUrl:'/new.png',sortOrder:0,isActive:true,homeVisible:true,homeOrder:4,homeLabel:'Libellé BO',homeImageUrl:'/home.png',catalogueVisible:true};assert.equal((await references.saveReference('category',request(input),'c')).status,200);let output=publicPresentation.visibleHome((await publicPresentation.getPublicPresentation()).categories);assert.equal(output.length,1);assert.equal(output[0].homeLabel,'Libellé BO');assert.equal(output[0].homeImageUrl,'/home.png');assert.equal(output[0].homeOrder,4);assert.equal((await references.saveReference('category',request({...input,homeVisible:false}),'c')).status,200);output=publicPresentation.visibleHome((await publicPresentation.getPublicPresentation()).categories);assert.deepEqual(output,[]);});
test('BO fournisseur vers bandeau : logo, lien, ordre et suppression visuelle',async()=>{settings.set('cms.catalogue.ready',{key:'cms.catalogue.ready',value:true});suppliers.set('s',{id:'s',name:'Partenaire',slug:'partenaire',isActive:true,presentationConfigured:true});const input={name:'Partenaire',slug:'partenaire',logoUrl:'/logo.png',contactName:null,email:null,phone:null,website:null,averageLeadTime:null,internalNotes:null,isActive:true,homeVisible:true,homeOrder:2,homeHref:'https://partner.test'};assert.equal((await references.saveReference('supplier',request(input),'s')).status,200);const output=publicPresentation.visibleHome((await publicPresentation.getPublicPresentation()).suppliers);assert.equal(output.length,1);assert.equal(output[0].logoUrl,'/logo.png');assert.equal(output[0].homeHref,'https://partner.test');assert.equal((await references.saveReference('supplier',request({...input,homeVisible:false}),'s')).status,200);assert.equal(publicPresentation.visibleHome((await publicPresentation.getPublicPresentation()).suppliers).length,0);});
const variant={code:'BO-1',name:'Variante',label:'BO',priceHt:12,stock:0,weightKg:null,packageLengthCm:null,packageWidthCm:null,packageHeightCm:null,leadTime:'',imageReference:'',shippingMode:null,options:[{label:'Taille',value:'L'}]};
test('API variantes : création, modification, suppression et provenance protégée',async()=>{const response=await variantApi.POST(request(variant,'POST'),context);assert.equal(response.status,201);const {item}=await response.json();assert.equal(item.sourceData.adminCreated,true);assert.deepEqual(item.options,{Taille:'L'});assert.equal((await variantApi.PATCH(request({...variant,id:item.id,label:'Nouveau'},'PATCH'),context)).status,200);assert.equal(variants.get(item.id).label,'Nouveau');assert.equal((await variantApi.DELETE(request({id:item.id},'DELETE'),context)).status,200);assert.equal(variants.size,0);});
test('API variantes : source fournisseur, commande et rôle sans droits bloqués',async()=>{variants.set('v1',{...variant,id:'v1',productId:'p1',sourceData:{supplier:true},_count:{orderItems:0}});assert.equal((await variantApi.DELETE(request({id:'v1'},'DELETE'),context)).status,403);variants.get('v1').sourceData={adminCreated:true};variants.get('v1')._count.orderItems=1;assert.equal((await variantApi.DELETE(request({id:'v1'},'DELETE'),context)).status,409);admin.role='CONTENT_EDITOR';assert.equal((await variantApi.POST(request(variant,'POST'),context)).status,403);assert.equal(variants.size,1);});

test('produit représentatif : sa principale personnalisée est utilisée pour la home et le catalogue',async()=>{settings.set('cms.catalogue.ready',{key:'cms.catalogue.ready',value:true});categories.set('c',{id:'c',name:'Catégorie',slug:'cat',parentId:null,homeParentId:null,imageUrl:'/ancienne.png',homeImageUrl:'/ancienne-home.png',representativeProductId:'p1',representativeProduct:{media:[{url:'/source.png'}],presentation:{value:{media:[{url:'/principale-bo.png',sortOrder:0,isPrimary:true,enabled:true,altText:''}]}}},products:[],isActive:true,homeVisible:true,presentationConfigured:true,publicTags:[]});const {categories:output}=await publicPresentation.getPublicPresentation();assert.equal(output[0].imageUrl,'/principale-bo.png');assert.equal(output[0].homeImageUrl,'/principale-bo.png');});
const classification=require('../../../app/api/admin/catalogue/[id]/classification/route') as typeof import('../../../app/api/admin/catalogue/[id]/classification/route');
test('classement manuel : fournisseur/catégorie modifiables, identifiants protégés après publication',async()=>{products.get('p1').sourceData={adminCreated:true};products.get('p1').slug='fiche';products.get('p1').publicationStatus='DRAFT';products.get('p1')._count={orderItems:0};categories.set('c',{id:'c'});suppliers.set('s',{id:'s'});const data={code:'SRC',slug:'fiche',categoryId:'c',supplierId:'s'};assert.equal((await classification.PATCH(request(data,'PATCH'),context)).status,200);assert.equal(products.get('p1').supplierId,'s');products.get('p1').publicationStatus='PUBLISHED';assert.equal((await classification.PATCH(request({...data,slug:'nouvelle-fiche'},'PATCH'),context)).status,409);assert.equal(products.get('p1').slug,'fiche');});

test('initialisation : champs Category déjà saisis dans la première livraison conservés',async()=>{categories.set('existing',{id:'existing',slug:'levage',name:'Nom existant',description:'Description existante',seoTitle:'SEO existant',seoDescription:'SEO description',imageUrl:'/image-deja-saisie.png',isActive:true,sortOrder:7,presentationConfigured:false});await initializer.initializePresentation(db);const item=categories.get('existing');assert.equal(item.name,'Nom existant');assert.equal(item.description,'Description existante');assert.equal(item.seoTitle,'SEO existant');assert.equal(item.imageUrl,'/image-deja-saisie.png');assert.equal(item.sortOrder,7);assert.ok(item.homeImageUrl);});
