import { test,beforeEach } from 'node:test';import assert from 'node:assert/strict';import Module from 'node:module';
const originalLoad=(Module as any)._load;(Module as any)._load=function(id:string,...args:any[]){if(id==='server-only')return {};return originalLoad.call(this,id,...args);};
let product:any,categoryRows:any[],ready=true;
const db:any={category:{findMany:async()=>categoryRows},siteSetting:{findUnique:async()=>({value:ready})},product:{findUnique:async()=>product,findMany:async()=>product?[product]:[]}};
const filename=require.resolve('../../db/prisma'),m=new Module(filename);m.filename=filename;m.loaded=true;m.exports={prisma:db};require.cache[filename]=m;
const repository=require('../../catalogue/database-repository') as typeof import('../../catalogue/database-repository');
beforeEach(()=>{ready=true;categoryRows=[{id:'root',slug:'nouvel-univers',homeParentId:null,presentationConfigured:true,isActive:true,catalogueVisible:true},{id:'family',slug:'nouvelle-famille',homeParentId:'root',presentationConfigured:true,isActive:true,catalogueVisible:true}];product={id:'p1',slug:'fiche',code:'SKU',supplierCode:'SOURCE',parentCode:null,name:'Source',shortName:null,description:'Source',detailedDescription:'Source longue',priceHt:123,minPriceHt:null,maxPriceHt:null,stock:8,weightKg:null,packageLengthCm:null,packageWidthCm:null,packageHeightCm:null,leadTime:'10 jours',shippingMode:'QUOTE',imageReference:'SKU',publicationStatus:'PUBLISHED',featured:false,sortOrder:0,experienceType:'STANDARD',configuratorFamily:null,optionSchema:[],sourceData:{},categoryId:'family',category:{id:'family',slug:'nouvelle-famille',name:'Famille'},supplier:{name:'Source fournisseur',isActive:true,presentationConfigured:true},features:[],media:[],documents:[],variants:[],presentation:{value:{name:'Nom commercial BO',description:'Description BO',featured:true,sortOrder:2,media:[{url:'/bo.png',isPrimary:true,sortOrder:0,enabled:true,altText:'BO'}],faq:[{question:'Question BO',answer:'Réponse BO'}],documents:[{name:'Notice BO',type:'OTHER',url:'/bo.pdf',sortOrder:0,isPublic:true}]}}};});
test('front produit : une nouvelle famille BO résout son univers, ses URL et ses overrides',async()=>{const items=await repository.getDatabaseProductsByCategory('nouvel-univers');assert.equal(items.length,1);assert.equal(items[0].name,'Nom commercial BO');assert.equal(items[0].description,'Description BO');assert.equal(items[0].categorySlug,'nouvel-univers');assert.equal(items[0].href,'/catalogue/nouvel-univers/fiche');assert.equal(items[0].media?.[0].url,'/bo.png');assert.equal(items[0].faq?.[0].question,'Question BO');assert.equal(items[0].documents?.[0].name,'Notice BO');assert.equal(items[0].priceHT,123);const detail=await repository.getDatabaseProductBySlug('nouvel-univers','fiche');assert.equal(detail?.name,'Nom commercial BO');});
test('front produit : catégorie/fournisseur désactivés et produit caché ne sont pas publiés',async()=>{categoryRows[0].catalogueVisible=false;assert.deepEqual(await repository.getDatabaseProductsByCategory('nouvel-univers'),[]);categoryRows[0].catalogueVisible=true;product.supplier.isActive=false;assert.equal(await repository.getDatabaseProductBySlug('nouvel-univers','fiche'),undefined);product.supplier.isActive=true;product.publicationStatus='HIDDEN';assert.equal(await repository.getDatabaseProductBySlug('nouvel-univers','fiche'),undefined);});
test('front produit : classification override change la famille publique sans déplacer la source',async()=>{categoryRows.push({id:'other',slug:'autre-univers',homeParentId:null,presentationConfigured:true,isActive:true,catalogueVisible:true});product.presentation.value.categoryId='other';const items=await repository.getDatabaseProductsByCategory('autre-univers');assert.equal(items.length,1);assert.equal(items[0].categoryId,'other');assert.equal(product.categoryId,'family');assert.equal(items[0].href,'/catalogue/autre-univers/fiche');});
test('front produit : dernière donnée fournisseur visible, personnalisation conservée et remise à la source fonctionnelle',async()=>{product.name='Dernier import';product.priceHt=456;const customized=await repository.getDatabaseProductBySlug('nouvel-univers','fiche');assert.equal(customized?.name,'Nom commercial BO');assert.equal(customized?.priceHT,456);product.presentation.value={};assert.equal((await repository.getDatabaseProductBySlug('nouvel-univers','fiche'))?.name,'Dernier import');});
test('front produit : une fiche configurateur masquée ne réapparaît pas depuis le snapshot',async()=>{product.slug='potence-sur-fut';product.publicationStatus='HIDDEN';assert.equal(await repository.getDatabaseProductBySlug('levage','potence-sur-fut'),undefined);product=null;assert.equal(await repository.getDatabaseProductBySlug('levage','potence-sur-fut'),undefined);ready=false;assert.ok(await repository.getDatabaseProductBySlug('levage','potence-sur-fut'));});

test('classification : ancienne URL produit continue de résoudre le slug pour redirection canonique',async()=>{const detail=await repository.getDatabaseProductBySlug('ancienne-categorie','fiche');assert.equal(detail?.href,'/catalogue/nouvel-univers/fiche');});
