"use client";

import { useState } from "react";
import { Check, KeyRound, MoreHorizontal, Plus, Search, ShieldCheck, UserCog, UserPlus, X } from "lucide-react";

const initialUsers = [
  { initials: "AD", name: "Aymeric Djeridi", email: "aymeric@oyste.fr", role: "Super administrateur", status: "Actif", last: "Aujourd’hui, 11:42" },
  { initials: "CM", name: "Claire Martin", email: "claire@oyste.fr", role: "Catalogue & contenus", status: "Actif", last: "Hier, 17:08" },
  { initials: "JL", name: "Julien Laurent", email: "julien@oyste.fr", role: "Commandes", status: "Actif", last: "15 juillet, 08:31" },
  { initials: "SB", name: "Sophie Bernard", email: "sophie@oyste.fr", role: "Lecture seule", status: "Invité", last: "Invitation envoyée" },
];

export default function AdminUsersManager() {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  return <>
    <div className="mt-7 flex flex-col gap-3 rounded-[1.5rem] border border-slate-200 bg-white p-4 shadow-sm sm:flex-row"><div className="flex flex-1 items-center gap-3 rounded-xl bg-slate-100 px-4 py-3"><Search size={17} className="text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechercher un administrateur…" className="w-full bg-transparent text-sm outline-none" /></div><button onClick={() => setOpen(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#007f8f] px-4 py-3 text-xs font-black text-white"><UserPlus size={17} /> Ajouter un administrateur</button></div>
    <section className="mt-5 overflow-hidden rounded-[1.5rem] border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4"><h2 className="text-lg font-black">Équipe d’administration</h2><p className="mt-1 text-xs text-slate-400">Gérez les accès et les permissions du back-office.</p></div><div className="divide-y divide-slate-100">{initialUsers.filter((user) => `${user.name} ${user.email}`.toLowerCase().includes(query.toLowerCase())).map((user) => <article key={user.email} className="grid gap-4 px-5 py-4 md:grid-cols-[minmax(240px,1fr)_210px_110px_170px_44px] md:items-center"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-cyan-50 text-xs font-black text-[#007f8f]">{user.initials}</div><div><p className="text-sm font-black">{user.name}</p><p className="mt-1 text-xs text-slate-400">{user.email}</p></div></div><span className="inline-flex items-center gap-2 text-xs font-black text-slate-600"><ShieldCheck size={16} className="text-[#007f8f]" />{user.role}</span><span className={`w-fit rounded-full px-2.5 py-1 text-[10px] font-black ${user.status === "Actif" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{user.status}</span><p className="text-xs font-bold text-slate-400">{user.last}</p><button className="rounded-xl p-2 text-slate-400 hover:bg-slate-100"><MoreHorizontal size={18} /></button></article>)}</div></section>
    <section className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[
      ["Super administrateur", "Accès total au site, aux utilisateurs et aux paramètres."],
      ["Catalogue & contenus", "Produits, médias, documents, catégories et pages du site."],
      ["Commandes", "Commandes, clients, paiements et expéditions."],
      ["Lecture seule", "Consultation sans possibilité de modification."],
    ].map(([title, text]) => <article key={title} className="rounded-[1.4rem] border border-slate-200 bg-white p-5 shadow-sm"><UserCog size={19} className="text-[#007f8f]" /><h3 className="mt-4 text-sm font-black">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p></article>)}</section>

    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/55 p-4 backdrop-blur-sm"><div className="w-full max-w-xl rounded-[1.75rem] bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-orange-600">Nouvel accès</p><h2 className="mt-2 text-2xl font-black">Ajouter un administrateur</h2></div><button onClick={() => setOpen(false)} className="rounded-xl p-2 hover:bg-slate-100"><X size={20} /></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-xs font-black text-slate-600">Prénom<input className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-[#007f8f]" /></label><label className="text-xs font-black text-slate-600">Nom<input className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-[#007f8f]" /></label><label className="text-xs font-black text-slate-600 sm:col-span-2">Adresse e-mail<input type="email" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-[#007f8f]" /></label><label className="text-xs font-black text-slate-600 sm:col-span-2">Rôle<select className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none"><option>Catalogue & contenus</option><option>Commandes</option><option>Lecture seule</option><option>Super administrateur</option></select></label></div><div className="mt-5 rounded-2xl bg-slate-50 p-4 text-xs leading-5 text-slate-500"><KeyRound size={17} className="mb-2 text-[#007f8f]" />Une invitation sécurisée sera envoyée par e-mail. L’utilisateur choisira son mot de passe lors de sa première connexion.</div><div className="mt-6 flex justify-end gap-2"><button onClick={() => setOpen(false)} className="rounded-xl border border-slate-200 px-4 py-3 text-xs font-black">Annuler</button><button onClick={() => setOpen(false)} className="inline-flex items-center gap-2 rounded-xl bg-[#007f8f] px-5 py-3 text-xs font-black text-white"><Check size={16} /> Envoyer l’invitation</button></div></div></div>}
  </>;
}
