"use client";
import AssetUploadButton from "./AssetUploadButton";
import { useState } from "react";
import { editorialDescriptors } from "@/lib/editorial-defaults";
import type { EditorialValue, EditorialPageId } from "@/lib/editorial-validation";
import CollectionEditor, { type CollectionField } from "./CollectionEditor";
const labels:Record<string,string>={title:"Titre",text:"Texte",question:"Question",answer:"Réponse",href:"Lien",icon:"Icône",label:"Libellé",value:"Valeur",enabled:"Visible",order:"Ordre"};
const iconOptions=['Compass','Boxes','ShieldCheck','Search','SlidersHorizontal','ShoppingCart','UserRound','FileText','Headphones','CheckCircle2','PackageCheck','Truck','Factory','Mail','Clock3'].map(value=>({value,label:value}));
export default function EditorialEditor(){const [id,setId]=useState<EditorialPageId|null>(null),[value,setValue]=useState<EditorialValue|null>(null),[writable,setWritable]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function open(next:EditorialPageId){setBusy(true);setMessage('');try{const response=await fetch(`/api/admin/editorial/${next}`);const data=await response.json();if(!response.ok)throw Error(data.error);setValue(data.value);setWritable(data.writable);setId(next);}catch(e){setMessage(String(e));}finally{setBusy(false);}}
 async function save(){setBusy(true);setMessage('');try{const response=await fetch(`/api/admin/editorial/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});const data=await response.json();if(!response.ok)throw Error(data.error);setValue(data.value);setMessage('Contenu enregistré, visible sur le site.');}catch(e){setMessage(String(e));}finally{setBusy(false);}}
 const descriptor=id?editorialDescriptors[id]:null;
 return <section className="mt-8 rounded-2xl border bg-white p-6"><h2 className="text-xl font-black">Pages et blocs commerciaux</h2><div className="my-5 flex flex-wrap gap-3">{Object.entries(editorialDescriptors).map(([key,page])=><button key={key} type="button" disabled={busy} onClick={()=>open(key as EditorialPageId)} className="rounded-xl border px-4 py-3 font-bold">{page.title}</button>)}</div>{value&&descriptor&&<div className="space-y-6"><h3 className="text-xl font-bold">{descriptor.title}</h3>{descriptor.fields.map(field=><label className="block text-sm font-bold" key={field.key}>{field.label}{field.kind==='link'||field.kind==='image'?<input value={value.fields[field.key]} disabled={!writable||busy} onChange={e=>setValue({...value,fields:{...value.fields,[field.key]:e.target.value}})} className="mt-2 w-full rounded-xl border p-3"/>:<textarea rows={3} value={value.fields[field.key]} disabled={!writable||busy} onChange={e=>setValue({...value,fields:{...value.fields,[field.key]:e.target.value}})} className="mt-2 w-full rounded-xl border p-3"/>}{field.kind==='image' && <AssetUploadButton scope="cms" disabled={!writable||busy} onUpload={url=>setValue({...value,fields:{...value.fields,[field.key]:url}})}/>}</label>)}{descriptor.collections.map(collection=>{const fields:CollectionField[]=collection.keys.map(key=>({key,label:labels[key]||key,type:key==='enabled'?'boolean':key==='order'?'number':key==='icon'?'select':['text','answer'].includes(key)?'textarea':'text',options:key==='icon'?iconOptions:undefined}));const initial=Object.fromEntries(collection.keys.map(key=>[key,key==='enabled'?true:key==='order'?0:key==='icon'?'Compass':'']));return <details key={collection.name} open className="rounded-xl border p-4"><summary className="mb-4 font-bold">{({pageSections:'Sections de la page : visibilité et ordre',commitments:'Engagements',pillars:'Piliers',platformServices:'Services',journeySteps:'Étapes',modes:'Modes de livraison',faq:'Questions fréquentes',contactCards:'Moyens de contact',promises:'Engagements de contact'} as Record<string,string>)[collection.name]||'Liste commerciale'}</summary><CollectionEditor allowAdd={collection.mode!=="sections"} allowRemove={collection.mode!=="sections"} value={value.collections[collection.name]} fields={fields} initialItem={initial} disabled={!writable||busy} onChange={items=>setValue({...value,collections:{...value.collections,[collection.name]:items as EditorialValue['collections'][string]}})}/></details>;})}<button type="button" disabled={!writable||busy} onClick={save} className="rounded-xl bg-[#007f8f] px-6 py-3 font-bold text-white">{busy?'Enregistrement…':'Enregistrer les modifications'}</button></div>}{message&&<p className="mt-4 text-sm font-bold" role="status">{message}</p>}</section>;
}
