"use client";
import { useState } from "react";
import { CheckCircle2, FileSpreadsheet, RefreshCw, ShieldCheck, TriangleAlert } from "lucide-react";

type AuditItem={id:string;code:string;name:string;supplier:string;currentPath:string;targetPath:string;match:string};
type Unresolved={id:string;code:string;name:string;supplier:string;reason:string};
type Audit={version:string;source:string;total:number;audited:number;excludedStockman:Unresolved[];corrections:AuditItem[];correct:AuditItem[];unresolved:Unresolved[]};

export default function ExcelCategorySyncCard(){
 const [audit,setAudit]=useState<Audit|null>(null);const [loading,setLoading]=useState(false);const [applying,setApplying]=useState(false);const [error,setError]=useState("");
 async function loadAudit(){setLoading(true);setError("");try{const r=await fetch("/api/admin/catalogue/excel-category-sync",{cache:"no-store"});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||"Audit impossible.");setAudit(p);}catch(e){setError(e instanceof Error?e.message:"Audit impossible.");}finally{setLoading(false);}}
 async function apply(){if(!audit?.corrections.length)return;const expected=`APPLIQUER ${audit.corrections.length}`;const confirmation=window.prompt(`Correction globale des catégories depuis l’Excel de référence.\n\n${audit.corrections.length} produit(s) seront reclassés.\nLes références ambiguës ou absentes ne seront PAS modifiées.\n\nTapez exactement ${expected} pour confirmer.`);if(confirmation!==expected)return;setApplying(true);setError("");try{const r=await fetch("/api/admin/catalogue/excel-category-sync",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({expected:audit.corrections.length})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||"Correction impossible.");await loadAudit();}catch(e){setError(e instanceof Error?e.message:"Correction impossible.");}finally{setApplying(false);}}
 return <section className="mt-5 rounded-[1.5rem] border border-emerald-200 bg-emerald-50/60 p-5 shadow-sm">
  <div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><div className="flex items-center gap-2 text-sm font-black text-slate-950"><FileSpreadsheet size={18} className="text-emerald-700"/>Synchronisation catégories Excel · V2.10.24.1</div><p className="mt-2 max-w-5xl text-xs font-bold leading-5 text-slate-600">Le fichier <b>Copie de BDD DATAPLUG FINAL (003)(4).xlsx</b> reste la source de vérité du catalogue historique. <b>STOCKMAN est exclu</b> de cet audit : ses catégories sont pilotées par le breadcrumb Stockman déjà traité. Matching par fournisseur + référence produit, puis référence parent quand elle est non ambiguë.</p></div><button type="button" onClick={()=>void loadAudit()} disabled={loading||applying} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-xs font-black text-white disabled:opacity-50"><RefreshCw size={15} className={loading?"animate-spin":""}/>{loading?"Audit…":"Auditer les catégories Excel"}</button></div>
  {error?<div className="mt-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-xs font-bold text-red-700">{error}</div>:null}
  {audit?<><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric value={audit.total} label="Produits en base"/><Metric value={audit.excludedStockman.length} label="STOCKMAN exclus"/><Metric value={audit.correct.length} label="Déjà corrects"/><Metric value={audit.corrections.length} label="À reclasser"/><Metric value={audit.unresolved.length} label="Non résolus / ambigus"/></div>
   <div className="mt-4 flex flex-col gap-3 rounded-2xl border border-emerald-200 bg-white p-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-3"><ShieldCheck size={20} className="mt-0.5 text-emerald-600"/><div><p className="text-xs font-black text-slate-900">Application protégée</p><p className="mt-1 text-[11px] font-semibold text-slate-500">Contrôle anti-dérive avant écriture. Les {audit.unresolved.length} cas non résolus restent intacts.</p></div></div><button type="button" onClick={()=>void apply()} disabled={applying||!audit.corrections.length} className="rounded-xl bg-emerald-600 px-5 py-3 text-xs font-black text-white disabled:opacity-40">{applying?"Application…":`Appliquer ${audit.corrections.length} correction(s)`}</button></div>
   {audit.corrections.length?<details className="mt-4 rounded-2xl border border-amber-200 bg-white" open><summary className="cursor-pointer px-4 py-3 text-xs font-black text-slate-900">Voir les changements proposés ({audit.corrections.length})</summary><div className="max-h-[420px] overflow-auto border-t border-amber-100 p-3">{audit.corrections.slice(0,250).map(i=><div key={i.id} className="mb-2 rounded-xl border border-slate-100 p-3 text-[11px]"><p className="font-black text-slate-900">{i.code} · {i.name} <span className="ml-2 text-slate-400">{i.supplier}</span></p><div className="mt-2 grid gap-2 lg:grid-cols-2"><div className="rounded-lg bg-slate-50 p-2"><b>Actuelle :</b> {i.currentPath}</div><div className="rounded-lg bg-emerald-50 p-2 text-emerald-800"><b>Excel :</b> {i.targetPath}</div></div></div>)}{audit.corrections.length>250?<p className="p-3 text-xs font-bold text-slate-500">250 premiers affichés sur {audit.corrections.length}. L’application traite bien la totalité.</p>:null}</div></details>:null}
   {audit.excludedStockman.length?<details className="mt-4 rounded-2xl border border-sky-200 bg-white"><summary className="cursor-pointer px-4 py-3 text-xs font-black text-sky-800">STOCKMAN exclus de l’audit Excel ({audit.excludedStockman.length})</summary><div className="max-h-[300px] overflow-auto border-t border-sky-100 p-3">{audit.excludedStockman.slice(0,250).map(i=><div key={i.id} className="mb-2 rounded-xl border border-sky-100 bg-sky-50/50 p-3 text-[11px]"><p className="font-black text-slate-900">{i.code} · {i.name}</p><p className="mt-1 font-semibold text-sky-700">{i.reason}</p></div>)}</div></details>:null}
   {audit.unresolved.length?<details className="mt-3 rounded-2xl border border-orange-200 bg-white"><summary className="cursor-pointer px-4 py-3 text-xs font-black text-orange-800"><span className="inline-flex items-center gap-2"><TriangleAlert size={14}/>Voir les cas non résolus ({audit.unresolved.length})</span></summary><div className="max-h-[320px] overflow-auto border-t border-orange-100 p-3">{audit.unresolved.slice(0,250).map(i=><div key={i.id} className="mb-2 rounded-xl bg-orange-50 p-3 text-[11px]"><b>{i.code} · {i.name}</b> · {i.supplier}<div className="mt-1 text-orange-700">{i.reason}</div></div>)}</div></details>:null}
  </>:null}
 </section>;
}
function Metric({value,label}:{value:number;label:string}){return <div className="rounded-2xl border border-emerald-100 bg-white p-4"><p className="text-2xl font-black text-slate-950">{value}</p><p className="mt-1 text-[10px] font-black uppercase tracking-wide text-slate-500">{label}</p></div>}
