"use client";
import AssetUploadButton from "./AssetUploadButton";
import { useEffect, useState } from "react";
import { productPresentationSchema, type ProductPresentation } from "@/lib/catalogue/product-presentation";
import CollectionEditor, { type CollectionField } from "./CollectionEditor";
const input = "mt-1 w-full rounded-xl border border-slate-200 p-3 text-sm";
const scalars = [ ["configuratorHref", "Lien vers le configurateur personnalisé"], ["name", "Nom public"], ["shortName", "Nom court"], ["description", "Description courte"], ["detailedDescription", "Description détaillée"], ["seoTitle", "Titre SEO"], ["seoDescription", "Description SEO"], ["sortOrder", "Ordre de présentation"], ["featured", "Mettre en avant"] ] as const;
const lists = [ ["marketingBadges", "Badges commerciaux"], ["videoUrls", "Vidéos (une URL par ligne)"], ["relatedProductCodes", "Produits associés (références séparées par des virgules)"], ["accessoryProductCodes", "Accessoires (références séparées par des virgules)"] ] as const;
const collections: Array<{ key: "faq" | "features" | "media" | "documents" | "variantPresentation"; title: string; fields: CollectionField[]; initial: Record<string, unknown> }> = [
 { key: "faq", title: "Questions fréquentes", fields: [{ key: "question", label: "Question" }, { key: "answer", label: "Réponse", type: "textarea" }], initial: { question: "Nouvelle question", answer: "" } },
 { key: "features", title: "Caractéristiques publiques", fields: [{ key: "label", label: "Libellé" }, { key: "value", label: "Valeur" }], initial: { label: "Caractéristique", value: "" } },
 { key: "media", title: "Images : ordre, visibilité et image principale", fields: [{ key: "url", label: "Image (URL)", type: "image" }, { key: "altText", label: "Texte alternatif" }, { key: "enabled", label: "Afficher", type: "boolean" }, { key: "isPrimary", label: "Image principale", type: "primary" }], initial: { url: "", altText: "", enabled: true, isPrimary: false, sortOrder: 0 } },
 { key: "documents", title: "Documents", fields: [{ key: "name", label: "Nom" }, { key: "url", label: "Lien du document" }, { key: "type", label: "Type", type: "select", options: [{ value: "TECHNICAL_SHEET", label: "Fiche technique" }, { value: "INSTALLATION_MANUAL", label: "Notice" }, { value: "DIMENSION_DRAWING", label: "Plan" }, { value: "CERTIFICATE", label: "Certificat" }, { value: "COMMERCIAL_DOCUMENT", label: "Document commercial" }, { value: "OTHER", label: "Autre" }] }, { key: "isPublic", label: "Visible sur la fiche", type: "boolean" }], initial: { name: "Nouveau document", url: "", type: "OTHER", isPublic: true, sortOrder: 0 } },
 { key: "variantPresentation", title: "Présentation des variantes", fields: [{ key: "label", label: "Libellé public" }, { key: "enabled", label: "Afficher", type: "boolean" }], initial: {} },
];
export default function ProductPresentationEditor({ productId }: { productId: string }) {
 const [categories,setCategories]=useState<Array<{id:string;name:string}>>([]);
 const [draft, setDraft] = useState<Record<string, unknown>>({});
 const [selected, setSelected] = useState<string[]>([]);
 const [writable, setWritable] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
 async function load() {
  const response = await fetch(`/api/admin/catalogue/${encodeURIComponent(productId)}/presentation`); const result = await response.json();
  if (!response.ok) throw new Error(result.error || "Chargement impossible.");
  const product = result.product as Record<string, unknown>;
  const overrides = productPresentationSchema.parse(result.overrides);
  const media = (product.media as Array<Record<string, unknown>>).map((item, sortOrder) => ({ url: item.url, altText: item.altText || "", isPrimary: !!item.isPrimary, sortOrder, enabled: true }));
  const documents = (product.documents as Array<Record<string, unknown>>).map((item, sortOrder) => ({ name: item.name, url: item.url, type: item.type, isPublic: !!item.isPublic, sortOrder }));
  const features = (product.features as Array<Record<string, unknown>>).map(item => ({ label: item.label, value: item.value }));
  const variantPresentation = (product.variants as Array<Record<string, unknown>>).map((item, sortOrder) => ({ id: item.id, label: String(item.label || item.name), enabled: true, sortOrder }));
  setCategories(result.categories || []);
  setDraft({ ...product, media, documents, features, variantPresentation, ...overrides }); setSelected(Object.keys(overrides)); setWritable(result.writable);
 }
 useEffect(() => { load().catch(error => setMessage(error.message)); }, [productId]);
 function customize(key: string, enabled: boolean) { setSelected(keys => enabled ? [...keys.filter(item => item !== key), key] : keys.filter(item => item !== key)); }
 function toggle(key: string) { return <label className="mb-2 flex gap-2 text-xs font-bold text-[#007f8f]"><input type="checkbox" disabled={busy || !writable} checked={selected.includes(key)} onChange={e => customize(key, e.target.checked)} />Utiliser un contenu personnalisé (sinon suivre la source)</label>; }
 async function save() {
  setBusy(true); setMessage("");
  const data = Object.fromEntries(selected.map(key => [key, draft[key]]));
  const parsed = productPresentationSchema.safeParse(data);
  if (!parsed.success) { setMessage("Vérifiez les champs renseignés, les références et les liens."); setBusy(false); return; }
  try { const response = await fetch(`/api/admin/catalogue/${encodeURIComponent(productId)}/presentation`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(parsed.data) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Enregistrement impossible."); setMessage("Présentation enregistrée. Le site public utilise ces valeurs."); }
  catch (error) { setMessage(error instanceof Error ? error.message : "Enregistrement impossible."); }
  finally { setBusy(false); }
 }
 return <section className="my-6 rounded-2xl border bg-white p-5 md:p-7"><h2 className="text-2xl font-black">Présentation commerciale</h2><p className="my-3 text-sm text-slate-500">La personnalisation est indépendante des synchronisations fournisseur. Désactivez une personnalisation pour retrouver la dernière donnée source. Retirer une image, un document ou masquer une variante ici conserve les données fournisseur.</p>
 {message && <p role="status" className="my-3 rounded-xl bg-slate-100 p-3 text-sm">{message}</p>}
 <div className="my-5">{toggle("experienceType")}<label className="text-sm font-bold">Parcours public<select disabled={!selected.includes("experienceType") || busy || !writable} value={String(draft.experienceType || "STANDARD")} onChange={e=>setDraft({...draft,experienceType:e.target.value})} className={input}><option value="STANDARD">Fiche produit standard</option><option value="CONFIGURABLE">Fiche avec configurateur</option></select></label></div>
 <div className="my-5">{toggle("categoryId")}<label className="text-sm font-bold">Catégorie de présentation<select value={String(draft.categoryId || "")} disabled={!selected.includes("categoryId") || busy || !writable} onChange={e=>setDraft({...draft,categoryId:e.target.value || null})} className={input}><option value="">Sans catégorie</option>{categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label></div>
 <details><summary className="cursor-pointer font-bold">Textes, SEO et mises en avant</summary><div className="mt-4 grid gap-5 md:grid-cols-2">{scalars.map(([key, title]) => <div key={key}>{toggle(key)}<label className="text-xs font-bold">{title}{key === "featured" ? <input type="checkbox" disabled={!selected.includes(key) || busy || !writable} checked={!!draft[key]} onChange={e => setDraft({ ...draft, [key]: e.target.checked })} className="ml-3" /> : ["description", "detailedDescription", "seoDescription"].includes(key) ? <textarea rows={key === "detailedDescription" ? 12 : 4} disabled={!selected.includes(key) || busy || !writable} value={String(draft[key] ?? "")} onChange={e => setDraft({ ...draft, [key]: e.target.value })} className={input} /> : <input disabled={!selected.includes(key) || busy || !writable} type={key === "sortOrder" ? "number" : "text"} min={key === "sortOrder" ? 0 : undefined} value={String(draft[key] ?? "")} onChange={e => setDraft({ ...draft, [key]: key === "sortOrder" ? Number(e.target.value) : e.target.value })} className={input} />}</label></div>)}{lists.map(([key, title]) => <div key={key}>{toggle(key)}<label className="text-xs font-bold">{title}<textarea disabled={!selected.includes(key) || busy || !writable} value={Array.isArray(draft[key]) ? (draft[key] as string[]).join(key === "videoUrls" ? "\n" : ", ") : ""} onChange={e => setDraft({ ...draft, [key]: e.target.value.split(key === "videoUrls" ? /\n/ : /,/).map(item => item.trim()).filter(Boolean) })} className={input} /></label></div>)}</div></details>
 <div className="mt-5 space-y-4">{collections.map(collection => <details key={collection.key} className="rounded-xl border p-4"><summary className="cursor-pointer font-bold">{collection.title}</summary><div className="mt-3">{toggle(collection.key)}{(collection.key==="media"||collection.key==="documents") && <AssetUploadButton scope={collection.key==="media"?"catalogue":"documents"} disabled={busy||!writable} onUpload={(url,name)=>{customize(collection.key,true);const current=Array.isArray(draft[collection.key])?draft[collection.key] as unknown[]:[];const next=collection.key==="media"?{url,altText:name,enabled:true,isPrimary:current.length===0,sortOrder:current.length}:{url,name,type:"OTHER",isPublic:true,sortOrder:current.length};setDraft({...draft,[collection.key]:[...current,next]});}}/>}<CollectionEditor value={Array.isArray(draft[collection.key]) ? draft[collection.key] as Array<Record<string, unknown>> : []} onChange={items => setDraft({ ...draft, [collection.key]: items })} fields={collection.fields} initialItem={collection.initial} disabled={!selected.includes(collection.key) || busy || !writable} allowAdd={collection.key !== "variantPresentation"} allowRemove={collection.key !== "variantPresentation"} /></div></details>)}</div>
 <div className="mt-5 flex gap-4"><button type="button" disabled={busy} onClick={() => load().catch(error => setMessage(error.message))}>Recharger la source</button>{writable && <button type="button" disabled={busy} onClick={save} className="rounded-xl bg-[#007f8f] px-5 py-3 font-bold text-white">{busy ? "Enregistrement…" : "Enregistrer la présentation"}</button>}</div></section>;
}
