"use client";
import { useEffect,useState } from 'react';
import CollectionEditor from './CollectionEditor';
type Row=Record<string,any>;
const empty:Row={code:'',name:'',label:'',priceHt:0,stock:0,weightKg:null,packageLengthCm:null,packageWidthCm:null,packageHeightCm:null,leadTime:'',imageReference:'',shippingMode:null,options:[]};
export default function ProductVariantsEditor({productId}:{productId:string}){const [items,setItems]=useState<Row[]>([]),[draft,setDraft]=useState<Row|null>(null),[writable,setWritable]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);async function load(){const response=await fetch(`/api/admin/catalogue/${productId}/variants`);const data=await response.json();if(!response.ok)throw Error(data.error);setItems(data.items);setWritable(data.writable);}useEffect(()=>{load().catch(e=>setMessage(String(e)));},[productId]);
 async function save(method:'POST'|'PATCH'|'DELETE',row:Row){setBusy(true);setMessage('');try{const response=await fetch(`/api/admin/catalogue/${productId}/variants`,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(method==='DELETE'?{id:row.id}:row)});const data=await response.json();if(!response.ok)throw Error(data.error);await load();setDraft(null);setMessage('Variante enregistrée. Rechargez la présentation commerciale pour ajuster son ordre.');}catch(e){setMessage(String(e));}finally{setBusy(false);}}
 function edit(row:Row){setDraft({...empty,...Object.fromEntries(Object.keys(empty).map(key=>[key,key==='options'?Object.entries(row.options||{}).map(([label,value])=>({label,value})):['priceHt','stock','weightKg','packageLengthCm','packageWidthCm','packageHeightCm'].includes(key)?row[key]===null?null:Number(row[key]):row[key]??empty[key]])),id:row.id});}
 return <details className="my-5 rounded-2xl border bg-white p-5"><summary className="font-black">Variantes : création et données des variantes BO</summary><p className="my-3 text-sm">Les références importées suivent le fournisseur. Leurs libellés, visibilité et ordre sont personnalisables dans Présentation commerciale.</p>{items.map(row=><div key={row.id} className="flex flex-wrap items-center gap-4 border-b py-3"><span className="flex-1 font-bold">{row.code} — {row.label||row.name}</span><span>{row.editable?'Créée dans le BO':'Source fournisseur'}</span>{row.editable&&<><button type="button" disabled={!writable||busy} onClick={()=>edit(row)}>Modifier</button><button type="button" disabled={!writable||busy} onClick={()=>{if(window.confirm('Supprimer cette variante ?'))save('DELETE',row);}}>Supprimer</button></>}</div>)}<button type="button" disabled={!writable||busy} onClick={()=>setDraft({...empty})} className="my-4 font-bold text-[#007f8f]">Ajouter une variante</button>{draft&&<div className="grid gap-4 md:grid-cols-2">{Object.keys(empty).filter(key=>!['options','shippingMode'].includes(key)).map(key=><label key={key} className="text-sm font-bold">{({code:'Référence',name:'Nom',label:'Libellé public',priceHt:'Prix HT',stock:'Stock',weightKg:'Poids (kg)',packageLengthCm:'Longueur colis (cm)',packageWidthCm:'Largeur colis (cm)',packageHeightCm:'Hauteur colis (cm)',leadTime:'Délai',imageReference:'Référence image'} as Record<string,string>)[key]}<input className="mt-1 w-full rounded-xl border p-3" value={draft[key]??''} min={typeof empty[key]==='number'||empty[key]===null?0:undefined} type={typeof empty[key]==='number'||empty[key]===null?'number':'text'} onChange={e=>setDraft({...draft,[key]:typeof empty[key]==='number'?Number(e.target.value):empty[key]===null?e.target.value===''?null:Number(e.target.value):e.target.value})}/></label>)}<label>Transport<select value={draft.shippingMode||''} onChange={e=>setDraft({...draft,shippingMode:e.target.value||null})} className="mt-1 w-full rounded-xl border p-3"><option value="">Suivre le produit</option>{['INCLUDED','MESSAGERIE','AFFRETEMENT','QUOTE'].map(mode=><option key={mode}>{mode}</option>)}</select></label><div className="md:col-span-2"><CollectionEditor value={draft.options} fields={[{key:'label',label:'Caractéristique'},{key:'value',label:'Valeur'}]} initialItem={{label:'',value:''}} onChange={options=>setDraft({...draft,options})}/></div><button type="button" disabled={busy} onClick={()=>save(draft.id?'PATCH':'POST',draft)} className="rounded-xl bg-[#007f8f] p-3 font-bold text-white">Enregistrer la variante</button><button type="button" onClick={()=>setDraft(null)}>Annuler</button></div>}{message&&<p role="status" className="mt-3 text-sm">{message}</p>}</details>;
}
