"use client";
import { useMemo, useState } from "react";
import { Check, ChevronRight, Eye, FileText, Globe2, Home, LayoutPanelTop, Loader2, Menu, Plus, Save, Search, Settings, Trash2, X } from "lucide-react";
import type { CmsContent } from "@/lib/cms";

const cards = [
  { key: "home", icon: Home, title: "Page d’accueil", description: "Bannière principale, accroche, boutons et visuel de couverture." },
  { key: "navigation", icon: Menu, title: "Navigation principale", description: "Libellés, liens et ordre des entrées du menu principal." },
  { key: "topbar", icon: LayoutPanelTop, title: "En-tête & bandeau", description: "Message d’information, adresse e-mail et horaires." },
  { key: "footer", icon: Settings, title: "Pied de page", description: "Coordonnées, zone d’intervention et appel à l’action." },
  { key: "editorial", icon: FileText, title: "Pages éditoriales", description: "Introductions des pages Livraison et Contact." },
] as const;

type SectionKey = typeof cards[number]["key"];
const input = "mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none transition focus:border-[#007f8f] focus:ring-4 focus:ring-cyan-50";

export default function SiteContentManager({ initialContent }: { initialContent: CmsContent }) {
  const [content, setContent] = useState(initialContent);
  const [editing, setEditing] = useState<SectionKey | null>(null);
  const [query, setQuery] = useState("");
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState("");
  const filtered = useMemo(() => cards.filter(c => `${c.title} ${c.description}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const current = cards.find(c => c.key === editing);

  async function save() {
    setSaving(true); setError("");
    const response = await fetch("/api/admin/cms", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(content) });
    const result = await response.json().catch(() => ({}));
    if (!response.ok) { setError(result.error || "Enregistrement impossible."); setSaving(false); return; }
    setContent(result); setSaving(false); setSaved(true); setTimeout(() => setSaved(false), 1800);
  }
  function field(section: keyof CmsContent, key: string, value: string | boolean) {
    setContent(prev => ({ ...prev, [section]: { ...(prev[section] as object), [key]: value } }));
  }
  return <>
    <div className="mt-7 flex flex-col gap-3 rounded-[1.5rem] border border-slate-200 bg-white p-4 shadow-sm sm:flex-row sm:items-center"><div className="flex flex-1 items-center gap-3"><Search size={18} className="text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher un contenu, une page ou un bloc…" className="w-full bg-transparent text-sm outline-none"/></div><a href="/" target="_blank" className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-xs font-black hover:border-[#007f8f] hover:text-[#007f8f]"><Eye size={16}/> Voir le site</a></div>
    <section className="mt-5 grid gap-4 lg:grid-cols-2">{filtered.map(section => { const Icon=section.icon; return <button key={section.key} onClick={()=>setEditing(section.key)} className="group flex items-center gap-4 rounded-[1.5rem] border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-[#007f8f]"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-cyan-50 text-[#007f8f]"><Icon size={21}/></div><div className="min-w-0 flex-1"><h2 className="text-sm font-black">{section.title}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{section.description}</p><p className="mt-2 text-[10px] font-black uppercase tracking-wider text-emerald-600">Synchronisé avec le site</p></div><ChevronRight className="text-slate-300 transition group-hover:translate-x-1 group-hover:text-[#007f8f]"/></button>})}</section>
    {editing && current && <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/45 backdrop-blur-sm"><div className="h-full w-full max-w-3xl overflow-y-auto bg-[#f3f6f8] shadow-2xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-200 bg-white px-6 py-5"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-orange-600">Éditeur de contenu</p><h2 className="mt-1 text-xl font-black">{current.title}</h2></div><button onClick={()=>setEditing(null)} className="rounded-xl p-2 hover:bg-slate-100"><X size={20}/></button></div><div className="p-6"><section className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm">
      {editing === "home" && <div className="space-y-5"><h3 className="text-sm font-black">Bannière principale</h3><label className="block text-xs font-black text-slate-600">Surtitre<input value={content.home.heroEyebrow} onChange={e=>field("home","heroEyebrow",e.target.value)} className={input}/></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-xs font-black text-slate-600">Titre<input value={content.home.heroTitle} onChange={e=>field("home","heroTitle",e.target.value)} className={input}/></label><label className="block text-xs font-black text-slate-600">Mise en avant<input value={content.home.heroAccent} onChange={e=>field("home","heroAccent",e.target.value)} className={input}/></label></div><label className="block text-xs font-black text-slate-600">Texte d’introduction<textarea rows={4} value={content.home.heroText} onChange={e=>field("home","heroText",e.target.value)} className={input}/></label><label className="block text-xs font-black text-slate-600">Image principale<input value={content.home.heroImage} onChange={e=>field("home","heroImage",e.target.value)} className={input}/></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-xs font-black text-slate-600">Bouton principal<input value={content.home.primaryLabel} onChange={e=>field("home","primaryLabel",e.target.value)} className={input}/></label><label className="block text-xs font-black text-slate-600">Lien principal<input value={content.home.primaryHref} onChange={e=>field("home","primaryHref",e.target.value)} className={input}/></label><label className="block text-xs font-black text-slate-600">Bouton secondaire<input value={content.home.secondaryLabel} onChange={e=>field("home","secondaryLabel",e.target.value)} className={input}/></label><label className="block text-xs font-black text-slate-600">Lien secondaire<input value={content.home.secondaryHref} onChange={e=>field("home","secondaryHref",e.target.value)} className={input}/></label></div></div>}
      {editing === "topbar" && <div className="space-y-5"><div className="flex items-center justify-between"><h3 className="text-sm font-black">Bandeau d’information</h3><label className="flex items-center gap-2 text-xs font-black"><input type="checkbox" checked={content.topbar.enabled} onChange={e=>field("topbar","enabled",e.target.checked)} /> Afficher</label></div><label className="block text-xs font-black text-slate-600">Message<input value={content.topbar.message} onChange={e=>field("topbar","message",e.target.value)} className={input}/></label><label className="block text-xs font-black text-slate-600">E-mail<input value={content.topbar.email} onChange={e=>field("topbar","email",e.target.value)} className={input}/></label><label className="block text-xs font-black text-slate-600">Horaires<input value={content.topbar.hours} onChange={e=>field("topbar","hours",e.target.value)} className={input}/></label></div>}
      {editing === "navigation" && <div><div className="flex items-center justify-between"><h3 className="text-sm font-black">Entrées du menu</h3><button onClick={()=>setContent(p=>({...p,navigation:[...p.navigation,{label:"Nouveau lien",href:"/"}]}))} className="inline-flex items-center gap-2 rounded-xl bg-cyan-50 px-3 py-2 text-xs font-black text-[#007f8f]"><Plus size={15}/> Ajouter</button></div><div className="mt-5 space-y-3">{content.navigation.map((item,index)=><div key={`${item.href}-${index}`} className="grid gap-3 rounded-xl border border-slate-200 p-4 sm:grid-cols-[1fr_1fr_auto]"><input value={item.label} onChange={e=>setContent(p=>({...p,navigation:p.navigation.map((n,i)=>i===index?{...n,label:e.target.value}:n)}))} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none"/><input value={item.href} onChange={e=>setContent(p=>({...p,navigation:p.navigation.map((n,i)=>i===index?{...n,href:e.target.value}:n)}))} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none"/><button onClick={()=>setContent(p=>({...p,navigation:p.navigation.filter((_,i)=>i!==index)}))} className="rounded-xl p-2 text-red-500 hover:bg-red-50"><Trash2 size={17}/></button></div>)}</div></div>}
      {editing === "footer" && <div className="space-y-5"><h3 className="text-sm font-black">Informations du pied de page</h3><label className="block text-xs font-black text-slate-600">Présentation<textarea rows={3} value={content.footer.description} onChange={e=>field("footer","description",e.target.value)} className={input}/></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-xs font-black text-slate-600">E-mail<input value={content.footer.email} onChange={e=>field("footer","email",e.target.value)} className={input}/></label><label className="block text-xs font-black text-slate-600">Zone d’intervention<input value={content.footer.area} onChange={e=>field("footer","area",e.target.value)} className={input}/></label></div><label className="block text-xs font-black text-slate-600">Horaires<textarea rows={2} value={content.footer.hours} onChange={e=>field("footer","hours",e.target.value)} className={input}/></label><hr className="border-slate-100"/><h3 className="text-sm font-black">Bloc d’appel à l’action</h3><label className="block text-xs font-black text-slate-600">Surtitre<input value={content.footer.ctaEyebrow} onChange={e=>field("footer","ctaEyebrow",e.target.value)} className={input}/></label><label className="block text-xs font-black text-slate-600">Titre<input value={content.footer.ctaTitle} onChange={e=>field("footer","ctaTitle",e.target.value)} className={input}/></label><label className="block text-xs font-black text-slate-600">Texte<textarea rows={3} value={content.footer.ctaText} onChange={e=>field("footer","ctaText",e.target.value)} className={input}/></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-xs font-black text-slate-600">Bouton<input value={content.footer.ctaLabel} onChange={e=>field("footer","ctaLabel",e.target.value)} className={input}/></label><label className="block text-xs font-black text-slate-600">Lien<input value={content.footer.ctaHref} onChange={e=>field("footer","ctaHref",e.target.value)} className={input}/></label></div></div>}
      {editing === "editorial" && <div className="space-y-6"><div><h3 className="text-sm font-black">Page Livraison</h3><label className="mt-4 block text-xs font-black text-slate-600">Titre<input value={content.editorial.deliveryTitle} onChange={e=>field("editorial","deliveryTitle",e.target.value)} className={input}/></label><label className="mt-4 block text-xs font-black text-slate-600">Introduction<textarea rows={3} value={content.editorial.deliveryIntro} onChange={e=>field("editorial","deliveryIntro",e.target.value)} className={input}/></label></div><hr className="border-slate-100"/><div><h3 className="text-sm font-black">Page Contact</h3><label className="mt-4 block text-xs font-black text-slate-600">Titre<input value={content.editorial.contactTitle} onChange={e=>field("editorial","contactTitle",e.target.value)} className={input}/></label><label className="mt-4 block text-xs font-black text-slate-600">Introduction<textarea rows={3} value={content.editorial.contactIntro} onChange={e=>field("editorial","contactIntro",e.target.value)} className={input}/></label></div></div>}
    </section>{error&&<p className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-xs font-bold text-red-700">{error}</p>}<div className="mt-5 grid gap-3 sm:grid-cols-2"><a href="/" target="_blank" className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-5 py-4 text-xs font-black"><Globe2 size={17}/> Prévisualiser le site</a><button onClick={save} disabled={saving} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#007f8f] px-5 py-4 text-xs font-black text-white disabled:opacity-60">{saving?<Loader2 className="animate-spin" size={17}/>:saved?<Check size={17}/>:<Save size={17}/>} {saving?"Enregistrement…":saved?"Contenu publié":"Enregistrer et publier"}</button></div></div></div></div>}
  </>;
}
