import { randomUUID } from 'node:crypto';
import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db/prisma';
import { getCurrentAdmin } from '@/lib/auth/admin-session';
import { canWriteCatalogue } from '@/lib/admin/catalogue-permissions';
import { isAdminVariant, variantInputSchema } from '@/lib/admin/variant-validation';
type Context={params:Promise<{id:string}>};
export async function GET(_:Request,{params}:Context){const admin=await getCurrentAdmin();if(!admin)return NextResponse.json({error:'Non autorisé'},{status:401});const {id}=await params;const product=await prisma.product.findUnique({where:{id},select:{id:true}});if(!product)return NextResponse.json({error:'Produit introuvable'},{status:404});const items=await prisma.productVariant.findMany({where:{productId:id},orderBy:{code:'asc'}});return NextResponse.json({items:items.map(item=>({...item,editable:isAdminVariant(item.sourceData)})),writable:canWriteCatalogue(admin)});}
async function mutate(request:Request,context:Context,method:'POST'|'PATCH'|'DELETE'){
 const admin=await getCurrentAdmin();if(!admin)return NextResponse.json({error:'Non autorisé'},{status:401});if(!canWriteCatalogue(admin))return NextResponse.json({error:'Modification non autorisée'},{status:403});const {id}=await context.params;const body=await request.json().catch(()=>null);const parsed=variantInputSchema.safeParse(body);if(method!=='DELETE'&&!parsed.success)return NextResponse.json({error:'Vérifiez la référence, les montants et les dimensions.'},{status:400});if(method==='DELETE'&&typeof body?.id!=='string')return NextResponse.json({error:'Variante manquante'},{status:400});
 try{const item=await prisma.$transaction(async tx=>{await tx.$executeRaw`SELECT pg_advisory_xact_lock(728194063)`;const product=await tx.product.findUnique({where:{id},select:{id:true}});if(!product)throw Error('NOT_FOUND');const variantId=method==='DELETE'?body.id:parsed.success?parsed.data.id:undefined;const existing=variantId?await tx.productVariant.findUnique({where:{id:variantId},include:{_count:{select:{orderItems:true}}}}):null;if(method!=='POST'&&(!existing||existing.productId!==id))throw Error('NOT_FOUND');if(existing&&!isAdminVariant(existing.sourceData))throw Error('SOURCE');if(existing?._count.orderItems)throw Error('ORDERED');let saved;if(method==='DELETE'){saved=await tx.productVariant.delete({where:{id:existing!.id}});}else{const {id:ignored,options,...data}=variantInputSchema.parse(body);const duplicate=await tx.productVariant.findFirst({where:{code:data.code,...(existing?{id:{not:existing.id}}:{})}});if(duplicate||await tx.product.findFirst({where:{code:data.code}}))throw Error('CODE');const values={...data,options:Object.fromEntries(options.map(item=>[item.label,item.value]))};saved=method==='POST'?await tx.productVariant.create({data:{id:randomUUID(),productId:id,sourceData:{adminCreated:true},...values}}):await tx.productVariant.update({where:{id:existing!.id},data:values});}
 await tx.auditLog.create({data:{action:`PRODUCT_VARIANT_${method}`,entityType:'ProductVariant',entityId:saved.id,userId:admin.id}});return saved;},{isolationLevel:'Serializable'});return NextResponse.json({item},{status:method==='POST'?201:200});}catch(e){const key=e instanceof Error?e.message:'';return NextResponse.json({error:key==='SOURCE'?'Les données techniques de cette variante sont gérées par le fournisseur. Personnalisez son libellé, sa visibilité et son ordre dans Présentation commerciale.':key==='ORDERED'?'Cette variante est liée à une commande et ne peut plus être modifiée ou supprimée.':key==='CODE'?'Cette référence est déjà utilisée.':key==='NOT_FOUND'?'Produit ou variante introuvable.':'Enregistrement impossible.'},{status:key==='NOT_FOUND'?404:key==='SOURCE'?403:409});}
}
export const POST=(r:Request,c:Context)=>mutate(r,c,'POST');export const PATCH=(r:Request,c:Context)=>mutate(r,c,'PATCH');export const DELETE=(r:Request,c:Context)=>mutate(r,c,'DELETE');
